### PR TITLE
fix: forecast for next day matches with data 

### PR DESCRIPTION
**Pull request by aarondrabeck**
first forecast in array is the next day, not current day

### CODE REVIEW

**Comment by Makin-Things** [comment]
I am guessing you are using met.no as your weather provider as it is missing the current days forecast.  Weather integrations should include the current days forecast as the forecast[0] element. There is an issue and a pending PR to fix that.
https://github.com/home-assistant/core/issues/74235
Your PR will break the card for every other integration that is doing the correct thing.

**Comment by Makin-Things** [comment]
I just noticed your location is the US, so probably a different integration being used. If it's the NWS one then things are complicated by the fact that it has 2 forecasts per day.

**Comment by aarondrabeck** [comment]
> I am guessing you are using met.no as your weather provider as it is missing the current days forecast. Weather integrations should include the current days forecast as the forecast[0] element. There is an issue and a pending PR to fix that. [home-assistant/core#74235](https://github.com/home-assistant/core/issues/74235) Your PR will break the card for every other integration that is doing the correct thing.

Yes that is true, I was using met.no and NWS has even more issues.  I wonder if matching the date might help in all these cases.

**Comment by jeffjensen** [comment]
> NWS has even more issues

Same for me.

**Comment by aarondrabeck** [comment]
Hopefully a better solution in #45

**Pull request closed without merging**
